export const weatherIconsDay = {
    0: 'clear-day',
    1: 'partly-cloudy-day',
    2: 'cloudy',
    3: 'overcast-day',
    45: 'fog',
    48: 'fog',
    51: 'drizzle',
    53: 'drizzle',
    55: 'drizzle',
    56: 'sleet',
    57: 'sleet',
    61: 'drizzle',
    63: 'rain',
    65: 'rain',
    66: 'sleet',
    67: 'sleet',
    71: 'snow',
    73: 'snow',
    75: 'snow',
    77: 'snow',
    80: 'rain',
    81: 'rain',
    82: 'rain',
    85: 'snow',
    86: 'snow',
    95: 'thunderstorms-day',
    '*': 'thunderstorms-day',
    96: 'thunderstorms-day-snow',
    ['99 *']: 'thunderstorms-day-snow'
}
export const weatherIconsNight = {
    0: 'clear-night',
    1: 'partly-cloudy-night',
    2: 'cloudy',
    3: 'overcast-night',
    45: 'fog',
    48: 'fog',
    51: 'drizzle',
    53: 'drizzle',
    55: 'drizzle',
    56: 'sleet',
    57: 'sleet',
    61: 'drizzle',
    63: 'rain',
    65: 'rain',
    66: 'sleet',
    67: 'sleet',
    71: 'snow',
    73: 'snow',
    75: 'snow',
    77: 'snow',
    80: 'rain',
    81: 'rain',
    82: 'rain',
    85: 'snow',
    86: 'snow',
    95: 'thunderstorms-night',
    '*': 'thunderstorms-night',
    96: 'thunderstorms-night-snow',
    ['99 *']: 'thunderstorms-night-snow'
}