export const weatherCodesEn = {
    0: 'Clear sky',
    1: 'Mainly clear',
    2: 'partly cloudy',
    3: 'overcast',
    45: 'Fog',
    48: 'depositing rime fog',
    51: 'drizzle light',
    53: 'drizzle moderate',
    55: 'drizzle heavy',
    56: 'Freezing Drizzle light',
    57: 'Freezing Drizzle dense',
    61: 'Rain light',
    63: 'Rain moderate',
    65: 'Rain heavy',
    66: 'Freezing Rain Light',
    67: 'Freezing Rain heavy',
    71: 'Snow fall slight',
    73: 'Snow fall moderate',
    75: 'Snow fall heavy',
    77: 'Snow grains',
    80: 'Rain showers slight',
    81: 'Rain showers moderate',
    82: 'Rain showers violent',
    85: 'Snow showers slight',
    86: 'Snow showers heavy',
    95: 'Thunderstorm Slight',
    '*': 'Thunderstorm heavy',
    96: 'hunderstorm with slight hail',
    ['99 *']: 'hunderstorm with heavy hail'
}
export const weatherCodesRu = {
    0: 'Ясное небо',
    1: 'В основном ясно',
    2: 'Переменная облачность',
    3: 'Пасмурно',
    45: 'Туман',
    48: 'Туман',
    51: 'Легкая Морось',
    53: 'Морось',
    55: 'Сильная Морось',
    56: 'Ледяная морось',
    57: 'Сильная ледяная морось',
    61: 'Небольшой дождь',
    63: 'Дождь',
    65: 'Сильный дождь',
    66: 'Ледяной дождь',
    67: 'Сильный ледяной дождь',
    71: 'Небольшой снег',
    73: 'Снег',
    75: 'Сильный снегопад',
    77: 'Сильный снегопад',
    80: 'Сильный дождь',
    81: 'Ливень',
    82: 'Сильный ливень',
    85: 'Небольшой снег',
    86: 'Сильный снегопад',
    95: 'Гроза',
    '*': 'Сильная гроза',
    96: 'Гроза с градом',
    ['99 *']: 'Сильная гроза с градом'
}